config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      # /users/:id/ ...
      get :following, :followers
      # GET /users/1/following => following action
      # GET /users/1/followers => followers action
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  # def help
  # end
  
   def about
   end
   
   def contact
   end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>

<h3>こっちにおいで、家族になろうよ</h3><br>

<h4><a href="/">You are zozo</a>は、一人でも多くの人たちを支えたい、そんな想いで作られました。<br>
    <br>おもいっきり楽しんで、おもいっきり笑える一日にしよう。<br>
    <br>みんなが幸せで、みんなを幸せにできる居場所。<br>
    <br>ちょっとの勇気が、あなたを一気に変える。<br>
    <br>みんなちがうけど、みんないっしょ。<br>
</h4>

<%= link_to image_tag("twitter.png", alt: "twitter logo"), 'https://twitter.com/ZOZOIncPR/' %>
<%= link_to image_tag("fb.jpg", alt: "fb logo"), 'https://www.facebook.com/ZOZOIncPR/' %>         

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the You are ZOZO at the
  <a href="https://corp.zozo.com/contact/">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
       <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Happy Tweets</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>You are ZOZO. You are Family.</h1>

  <p>
    <br>Welcome to the home page for
    <a href="/about">You are ZOZO</a>
    <br>Be unique.Be equal.<br>
  </p>

  <%= link_to "Be Family", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("zozotown.jpg", alt: "zozo logo"), 'http://zozo.jp/' %>
<% end %>